package io.k2dv.garden.blob.service;

import java.io.InputStream;

public interface StorageService {

    /**
     * Store an object at the given key. Key is generated by the caller.
     * contentLength must be provided — MinIO does not support chunked uploads.
     */
    void store(String key, String contentType, InputStream data, long contentLength);

    /** Delete the object at the given key. Idempotent — no error if key absent. */
    void delete(String key);

    /** Compute the public URL for a key: baseUrl + "/" + key. */
    String resolveUrl(String key);
}
