package io.k2dv.garden.order.model;

public enum OrderEventType {
    ORDER_PLACED,
    PAYMENT_CONFIRMED,
    ORDER_CANCELLED,
    ORDER_REFUNDED,
    ADMIN_REFUND_ISSUED,
    DISCOUNT_APPLIED,
    GIFT_CARD_APPLIED,
    FULFILLMENT_CREATED,
    FULFILLMENT_UPDATED,
    NOTE_ADDED,
    INVOICE_ISSUED,
    ORDER_APPROVAL_REQUESTED,
    ORDER_APPROVED,
    ORDER_APPROVAL_REJECTED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    RETURN_COMPLETED
}
