package io.k2dv.garden.shared.model;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.generator.EventType;

import java.time.Instant;
import java.util.UUID;

/**
 * Base entity for all Garden domain entities.
 *
 * <p>Primary key: UUIDv7 — time-ordered, B-tree friendly.
 * Generated by Hibernate via @UuidGenerator(style = TIME) (Hibernate 6.2+).
 *
 * <p>Timestamps: managed entirely by the database using clock_timestamp().
 * @Generated with EventType.INSERT / EventType.UPDATE instructs Hibernate to
 * re-read the column after write rather than using Instant.now() at the Java layer.
 * This is critical for @Transactional integration tests: clock_timestamp() returns
 * real wall-clock time even within a transaction, preserving row ordering.
 * Using @CreationTimestamp would call Instant.now() (= transaction start time)
 * and produce identical timestamps for all rows in a test.
 */
@MappedSuperclass
@Getter
public abstract class BaseEntity {

    @Id
    @UuidGenerator(style = UuidGenerator.Style.VERSION_7)
    private UUID id;

    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", insertable = false, updatable = false)
    private Instant createdAt;

    @Generated(event = {EventType.INSERT, EventType.UPDATE})
    @Column(name = "updated_at", insertable = false, updatable = false)
    private Instant updatedAt;
}
